//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropletExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DropletExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ***** BEGIN LICENSE BLOCK *****
        /// * Distributed under the BSD license:
        /// *
        /// * Copyright (c) 2010, Ajax.org B.V.
        /// * All rights reserved.
        /// * 
        /// * Redistribution and use in source and binary forms, with or without
        /// * modification, are permitted provided that the following conditions are met:
        /// *     * Redistributions of source code must retain the above copyright
        /// *       notice, this list of conditions and the following disclaimer.
        /// *     * Redistributions in binary form must reproduce the above copyright
        /// *   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ace {
            get {
                return ResourceManager.GetString("ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * CoffeeScript Compiler v1.7.1
        /// * http://coffeescript.org
        /// *
        /// * Copyright 2011, Jeremy Ashkenas
        /// * Released under the MIT License
        /// */
        ///(function(root){var CoffeeScript=function(){function require(e){return require[e]}return require[&quot;./helpers&quot;]=function(){var e={},t={exports:e};return function(){var t,n,i,r,o,s,a;e.starts=function(e,t,n){return t===e.substr(n,t.length)},e.ends=function(e,t,n){var i;return i=t.length,t===e.substr(e.length-i-(n||0),i)},e.repeat=o=function(e,t){var n;for(n=&quot;&quot;;t&gt;0;)1&amp;t&amp;&amp;(n+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string coffee_script {
            get {
                return ResourceManager.GetString("coffee_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .droplet-palette-canvas, .droplet-drag-canvas, .droplet-main-canvas, .droplet-lasso-select-canvas, .droplet-highlight-canvas {
        ///  position: absolute;
        ///}
        ///.droplet-main-canvas, .droplet-drag-canvas, .droplet-lasso-select-canvas, .droplet-highlight-canvas {
        ///  top: 0;
        ///}
        ///.droplet-drag-canvas {
        ///  z-index: 258;
        ///  margin-top: -2px;
        ///  margin-left: -1px;
        ///  opacity: 0.85;
        ///  -webkit-filter: drop-shadow( 5px 5px 5px #888 );
        ///  filter: drop-shadow( 5px 5px 5px #888 ); /* Same syntax as box-shadow */
        ///}
        ///.droplet-palette-canva [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string droplet {
            get {
                return ResourceManager.GetString("droplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(f){if(typeof exports===&quot;object&quot;&amp;&amp;typeof module!==&quot;undefined&quot;){module.exports=f()}else if(typeof define===&quot;function&quot;&amp;&amp;define.amd){define([],f)}else{var g;if(typeof window!==&quot;undefined&quot;){g=window}else if(typeof global!==&quot;undefined&quot;){g=global}else if(typeof self!==&quot;undefined&quot;){g=self}else{g=this}g.droplet = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require==&quot;function&quot;&amp;&amp;require;if(!u&amp;&amp;a)return a(o,!0);if(i)return i(o,!0);var  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string droplet_full {
            get {
                return ResourceManager.GetString("droplet_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] example {
            get {
                object obj = ResourceManager.GetObject("example", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Droplet Demo&lt;/title&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../css/droplet.css&quot;/&gt;
        ///    &lt;link href=&apos;http://fonts.googleapis.com/css?family=VT323&apos; rel=&apos;stylesheet&apos; type=&apos;text/css&apos;&gt;
        ///    &lt;style&gt;
        ///      #container {
        ///        position: absolute;
        ///        top: 45; bottom: 25; right: 25; left: 25;
        ///      }
        ///      #left-panel {
        ///        position: absolute;
        ///        top: 0; bottom: 0; width: 500px; left: 0;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example1 {
            get {
                return ResourceManager.GetString("example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=&quot;1.11.1&quot;,m=function(a,b){return new m.fn.init(a,b)},n=/^[\s\uFEFF\xA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_min {
            get {
                return ResourceManager.GetString("jquery_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace.define(&quot;ace/mode/coffee_highlight_rules&quot;,[&quot;require&quot;,&quot;exports&quot;,&quot;module&quot;,&quot;ace/lib/oop&quot;,&quot;ace/mode/text_highlight_rules&quot;], function(require, exports, module) {
        ///&quot;use strict&quot;;
        ///
        ///    var oop = require(&quot;../lib/oop&quot;);
        ///    var TextHighlightRules = require(&quot;./text_highlight_rules&quot;).TextHighlightRules;
        ///
        ///    oop.inherits(CoffeeHighlightRules, TextHighlightRules);
        ///
        ///    function CoffeeHighlightRules() {
        ///        var identifier = &quot;[$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*&quot;;
        ///
        ///        var keywords = (
        ///            &quot;this|t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mode_coffee {
            get {
                return ResourceManager.GetString("mode_coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace.define(&quot;ace/mode/doc_comment_highlight_rules&quot;,[&quot;require&quot;,&quot;exports&quot;,&quot;module&quot;,&quot;ace/lib/oop&quot;,&quot;ace/mode/text_highlight_rules&quot;], function(require, exports, module) {
        ///&quot;use strict&quot;;
        ///
        ///var oop = require(&quot;../lib/oop&quot;);
        ///var TextHighlightRules = require(&quot;./text_highlight_rules&quot;).TextHighlightRules;
        ///
        ///var DocCommentHighlightRules = function() {
        ///
        ///    this.$rules = {
        ///        &quot;start&quot; : [ {
        ///            token : &quot;comment.doc.tag&quot;,
        ///            regex : &quot;@[\\w\\d_]+&quot; // TODO: fix email addresses
        ///        }, {
        ///            token [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mode_javascript {
            get {
                return ResourceManager.GetString("mode_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ace.define(&quot;ace/theme/chrome&quot;,[&quot;require&quot;,&quot;exports&quot;,&quot;module&quot;,&quot;ace/lib/dom&quot;], function(require, exports, module) {
        ///
        ///exports.isDark = false;
        ///exports.cssClass = &quot;ace-chrome&quot;;
        ///exports.cssText = &quot;.ace-chrome .ace_gutter {\
        ///background: #ebebeb;\
        ///color: #333;\
        ///overflow : hidden;\
        ///}\
        ///.ace-chrome .ace_print-margin {\
        ///width: 1px;\
        ///background: #e8e8e8;\
        ///}\
        ///.ace-chrome {\
        ///background-color: #FFFFFF;\
        ///color: black;\
        ///}\
        ///.ace-chrome .ace_cursor {\
        ///color: black;\
        ///}\
        ///.ace-chrome .ace_invisible {\
        ///color: rgb(191, 191, 191);\
        ///} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string theme_chrome {
            get {
                return ResourceManager.GetString("theme_chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;no use strict&quot;;
        ///;(function(window) {
        ///if (typeof window.window != &quot;undefined&quot; &amp;&amp; window.document) {
        ///    return;
        ///}
        ///
        ///window.console = function() {
        ///    var msgs = Array.prototype.slice.call(arguments, 0);
        ///    postMessage({type: &quot;log&quot;, data: msgs});
        ///};
        ///window.console.error =
        ///window.console.warn = 
        ///window.console.log =
        ///window.console.trace = window.console;
        ///
        ///window.window = window;
        ///window.ace = window;
        ///
        ///window.onerror = function(message, file, line, col, err) {
        ///    console.error(&quot;Worker &quot; + (err ? err.stack : me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string worker_coffee {
            get {
                return ResourceManager.GetString("worker_coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;no use strict&quot;;
        ///;(function(window) {
        ///if (typeof window.window != &quot;undefined&quot; &amp;&amp; window.document) {
        ///    return;
        ///}
        ///
        ///window.console = function() {
        ///    var msgs = Array.prototype.slice.call(arguments, 0);
        ///    postMessage({type: &quot;log&quot;, data: msgs});
        ///};
        ///window.console.error =
        ///window.console.warn = 
        ///window.console.log =
        ///window.console.trace = window.console;
        ///
        ///window.window = window;
        ///window.ace = window;
        ///
        ///window.onerror = function(message, file, line, col, err) {
        ///    console.error(&quot;Worker &quot; + (err ? err.stack : me [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string worker_javascript {
            get {
                return ResourceManager.GetString("worker_javascript", resourceCulture);
            }
        }
    }
}
